# Generated by Django 2.2 on 2019-04-05 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redeye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='redeye.Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
